dist: xenial
language: minimal

git:
  quiet: true
  submodules: false

branches:
  only:
  - master
  - deploy

env:
# Carefull, also set it in the deploy section!
- NOTES_FILE=main

services:
- docker

script:
- docker run --rm -v $(pwd):/notes blang/latex /bin/bash -c "cd /notes; ./build.sh $NOTES_FILE"
- "./test.sh $NOTES_FILE"

deploy:
  provider: releases
  api_key:
    secure: ZvhMnkqhJc0rHh+jkafu36puDJLjq3i/dheELeqOHZn+vD8hgZ1A9zCB3nTI99ue2NPXqn8I/kZexuR+2XBQWXmt6+7ZwCHzLJ6oTF5OVwKZBpbmj685EkSbmlrqYJal5pecxRdx7DfXFFysR3JpzKv7Ye1OjJynmxjy9rpbo+UClUOGoI59YboVIagYhw1dZmzG0s/aa8+90DdpHHjI/QRFwRo0Ti19q3uxmjIPH1kY7xXilnzu4w+LIbuYoLQUQzl+d5b06Yj/t7d/azWNR62RurXPpHSf23a9jzu1EbVs5hqueSk+jUA0eamkDimzk+4gZwR6m9YJAGmMop4w2u1/KzHAYinc2JeZ/HiT93rNtIm4j3qJmmA9IaQBm94d42Qexj1aVIs8xw6CyntqiSK0UDUb0Qcc1uCx/o4dM1EpeZiz0XZHhRzABNMnbxBVq/6doZgpU/2VTVSePLkBV3p0phCqRKVt6Vw3kaj9BQeUS1Ha8wy2T3R3/sdMjQsvnNj1yHt/ZJCmfrb2KzcombM4AQc99Rw/pyKQZQ+kV77NevE8YpFffS0Hu/XHXvLY64EwenLO7gm6zdKrEwIZvSQD74ppiDNWZBKYkJpsF6edeFZaRN6ogLVeTSfCiKb7QcITk6k5Cf7RpLU8VNAQBOcZb0wDmyl/sRdtgNVqOJc=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: icl-notes/c493
